"""create tenants, users, projects

Revision ID: e3a39d4c3efb
Revises: 
Create Date: 2026-10-01 06:46:37.139607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a39d4c3efb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

        # --- Row-level security ---
    op.execute("ALTER TABLE users ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE users FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation_users ON users
        USING (tenant_id::text = current_setting('app.current_tenant', true))
    """)

    op.execute("ALTER TABLE projects ENABLE ROW LEVEL SECURITY")
    op.execute("ALTER TABLE projects FORCE ROW LEVEL SECURITY")
    op.execute("""
        CREATE POLICY tenant_isolation_projects ON projects
        USING (tenant_id::text = current_setting('app.current_tenant', true))
    """)

    # Non-superuser app role — RLS is ignored for superusers/table owners otherwise
    op.execute("DO $$ BEGIN "
               "IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'tenantshield_app') THEN "
               "CREATE ROLE tenantshield_app LOGIN PASSWORD 'change_me_locally'; "
               "END IF; END $$;")
    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON users, projects, tenants TO tenantshield_app")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS tenant_isolation_projects ON projects")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_users ON users")
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('tenants')
    # ### end Alembic commands ###
